services:
  facturasNuvi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:8000"
    container_name: facturasNuvi
    networks:
      - chatbotavr

networks:
  chatbotavr:
    driver: bridge
    external: true

